# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(598, 521)
                MainWindow.setStyleSheet("")
                MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
                MainWindow.setDocumentMode(False)
                MainWindow.setUnifiedTitleAndToolBarOnMac(False)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
                self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
                self.gridLayout_2.setObjectName("gridLayout_2")
                self.frameMainWindow = QtWidgets.QFrame(self.centralwidget)
                self.frameMainWindow.setStyleSheet("QFrame {\n"
                                                   "        background-color: rgb(24, 27, 40);\n"
                                                   "        border-radius: 10px;\n"
                                                   "        }\n"
                                                   "       ")
                self.frameMainWindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frameMainWindow.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frameMainWindow.setObjectName("frameMainWindow")
                self.gridLayout_3 = QtWidgets.QGridLayout(self.frameMainWindow)
                self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
                self.gridLayout_3.setObjectName("gridLayout_3")
                self.stackedWidgetContainer = QtWidgets.QStackedWidget(self.frameMainWindow)
                self.stackedWidgetContainer.setEnabled(True)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.stackedWidgetContainer.sizePolicy().hasHeightForWidth())
                self.stackedWidgetContainer.setSizePolicy(sizePolicy)
                self.stackedWidgetContainer.setStyleSheet("background-color: rgb(27, 32, 47);\n"
                                                          "                             color: rgb(255, 255, 255);\n"
                                                          "                         ")
                self.stackedWidgetContainer.setObjectName("stackedWidgetContainer")
                self.pageSetting = QtWidgets.QWidget()
                self.pageSetting.setObjectName("pageSetting")
                self.gridLayout_5 = QtWidgets.QGridLayout(self.pageSetting)
                self.gridLayout_5.setObjectName("gridLayout_5")
                self.frameBodyPage1 = QtWidgets.QFrame(self.pageSetting)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frameBodyPage1.sizePolicy().hasHeightForWidth())
                self.frameBodyPage1.setSizePolicy(sizePolicy)
                self.frameBodyPage1.setMinimumSize(QtCore.QSize(200, 0))
                self.frameBodyPage1.setStyleSheet("")
                self.frameBodyPage1.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frameBodyPage1.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frameBodyPage1.setObjectName("frameBodyPage1")
                self.gridLayout_4 = QtWidgets.QGridLayout(self.frameBodyPage1)
                self.gridLayout_4.setContentsMargins(50, 10, 50, 10)
                self.gridLayout_4.setVerticalSpacing(10)
                self.gridLayout_4.setObjectName("gridLayout_4")
                self.btnStop = QtWidgets.QPushButton(self.frameBodyPage1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
                self.btnStop.setSizePolicy(sizePolicy)
                self.btnStop.setMinimumSize(QtCore.QSize(75, 30))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.btnStop.setFont(font)
                self.btnStop.setStyleSheet("QPushButton {\n"
                                           "                                                         border-radius: 15px;\n"
                                           "                                                         border: 1px solid #FF5252;\n"
                                           "                                                         color: #FF5252;\n"
                                           "                                                         }\n"
                                           "                                                         QPushButton:hover {\n"
                                           "                                                         background: #FF5252;\n"
                                           "                                                         color: #ffffff;\n"
                                           "                                                         }\n"
                                           "                                                     ")
                self.btnStop.setObjectName("btnStop")
                self.gridLayout_4.addWidget(self.btnStop, 7, 6, 1, 1)
                spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                   QtWidgets.QSizePolicy.Expanding)
                self.gridLayout_4.addItem(spacerItem, 3, 0, 1, 1)
                spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                    QtWidgets.QSizePolicy.Expanding)
                self.gridLayout_4.addItem(spacerItem1, 1, 0, 1, 1)
                spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                    QtWidgets.QSizePolicy.Expanding)
                self.gridLayout_4.addItem(spacerItem2, 8, 1, 1, 1)
                self.groupBoxTypeRemind = QtWidgets.QGroupBox(self.frameBodyPage1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.groupBoxTypeRemind.sizePolicy().hasHeightForWidth())
                self.groupBoxTypeRemind.setSizePolicy(sizePolicy)
                self.groupBoxTypeRemind.setMinimumSize(QtCore.QSize(0, 178))
                self.groupBoxTypeRemind.setObjectName("groupBoxTypeRemind")
                self.gridLayout = QtWidgets.QGridLayout(self.groupBoxTypeRemind)
                self.gridLayout.setContentsMargins(9, -1, 9, -1)
                self.gridLayout.setObjectName("gridLayout")
                self.radioButtonType_Popup = QtWidgets.QRadioButton(self.groupBoxTypeRemind)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.radioButtonType_Popup.setFont(font)
                self.radioButtonType_Popup.setObjectName("radioButtonType_Popup")
                self.gridLayout.addWidget(self.radioButtonType_Popup, 0, 1, 1, 1)
                self.radioButtonType_Toast = QtWidgets.QRadioButton(self.groupBoxTypeRemind)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.radioButtonType_Toast.setFont(font)
                self.radioButtonType_Toast.setChecked(True)
                self.radioButtonType_Toast.setObjectName("radioButtonType_Toast")
                self.gridLayout.addWidget(self.radioButtonType_Toast, 0, 0, 1, 1)
                self.labelImageToast = QtWidgets.QLabel(self.groupBoxTypeRemind)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelImageToast.sizePolicy().hasHeightForWidth())
                self.labelImageToast.setSizePolicy(sizePolicy)
                self.labelImageToast.setMinimumSize(QtCore.QSize(200, 120))
                self.labelImageToast.setText("")
                self.labelImageToast.setPixmap(QtGui.QPixmap("images/toastNotify.jpg"))
                self.labelImageToast.setObjectName("labelImageToast")
                self.gridLayout.addWidget(self.labelImageToast, 1, 0, 1, 1)
                self.labelImagePopup = QtWidgets.QLabel(self.groupBoxTypeRemind)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.labelImagePopup.sizePolicy().hasHeightForWidth())
                self.labelImagePopup.setSizePolicy(sizePolicy)
                self.labelImagePopup.setMinimumSize(QtCore.QSize(200, 120))
                self.labelImagePopup.setText("")
                self.labelImagePopup.setPixmap(QtGui.QPixmap("images/popupWindow.jpg"))
                self.labelImagePopup.setObjectName("labelImagePopup")
                self.gridLayout.addWidget(self.labelImagePopup, 1, 1, 1, 1)
                self.gridLayout_4.addWidget(self.groupBoxTypeRemind, 4, 0, 1, 7)
                spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                                    QtWidgets.QSizePolicy.Expanding)
                self.gridLayout_4.addItem(spacerItem3, 6, 1, 1, 1)
                self.labelMinute = QtWidgets.QLabel(self.frameBodyPage1)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.labelMinute.setFont(font)
                self.labelMinute.setObjectName("labelMinute")
                self.gridLayout_4.addWidget(self.labelMinute, 2, 4, 1, 1)
                self.btnStart = QtWidgets.QPushButton(self.frameBodyPage1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
                self.btnStart.setSizePolicy(sizePolicy)
                self.btnStart.setMinimumSize(QtCore.QSize(75, 30))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                font.setStyleStrategy(QtGui.QFont.PreferDefault)
                self.btnStart.setFont(font)
                self.btnStart.setStyleSheet("QPushButton {\n"
                                            "                                                         border-radius: 15px;\n"
                                            "                                                         border: 1px solid #66BB6A;\n"
                                            "                                                         color: #66BB6A\n"
                                            "                                                         }\n"
                                            "                                                         QPushButton:hover {\n"
                                            "                                                         background-color: #66BB6A;\n"
                                            "                                                         color: #ffffff;\n"
                                            "                                                         }\n"
                                            "                                                     ")
                self.btnStart.setAutoDefault(False)
                self.btnStart.setDefault(False)
                self.btnStart.setFlat(False)
                self.btnStart.setObjectName("btnStart")
                self.gridLayout_4.addWidget(self.btnStart, 7, 5, 1, 1)
                spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                                    QtWidgets.QSizePolicy.Minimum)
                self.gridLayout_4.addItem(spacerItem4, 2, 5, 1, 2)
                self.labelUserName = QtWidgets.QLabel(self.frameBodyPage1)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.labelUserName.setFont(font)
                self.labelUserName.setObjectName("labelUserName")
                self.gridLayout_4.addWidget(self.labelUserName, 0, 0, 1, 1)
                self.spinBoxTime = QtWidgets.QSpinBox(self.frameBodyPage1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.spinBoxTime.sizePolicy().hasHeightForWidth())
                self.spinBoxTime.setSizePolicy(sizePolicy)
                self.spinBoxTime.setMinimumSize(QtCore.QSize(45, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.spinBoxTime.setFont(font)
                self.spinBoxTime.setMinimum(1)
                self.spinBoxTime.setMaximum(60)
                self.spinBoxTime.setProperty("value", 20)
                self.spinBoxTime.setObjectName("spinBoxTime")
                self.gridLayout_4.addWidget(self.spinBoxTime, 2, 3, 1, 1)
                self.lineEditUserName = QtWidgets.QLineEdit(self.frameBodyPage1)
                self.lineEditUserName.setMinimumSize(QtCore.QSize(0, 30))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEditUserName.setFont(font)
                self.lineEditUserName.setObjectName("lineEditUserName")
                self.gridLayout_4.addWidget(self.lineEditUserName, 0, 3, 1, 4)
                self.labelChooseTime = QtWidgets.QLabel(self.frameBodyPage1)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.labelChooseTime.setFont(font)
                self.labelChooseTime.setScaledContents(True)
                self.labelChooseTime.setObjectName("labelChooseTime")
                self.gridLayout_4.addWidget(self.labelChooseTime, 2, 0, 1, 3)
                self.checkBoxShowTips = QtWidgets.QCheckBox(self.frameBodyPage1)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.checkBoxShowTips.setFont(font)
                self.checkBoxShowTips.setChecked(True)
                self.checkBoxShowTips.setObjectName("checkBoxShowTips")
                self.gridLayout_4.addWidget(self.checkBoxShowTips, 5, 0, 1, 2)
                self.gridLayout_5.addWidget(self.frameBodyPage1, 0, 0, 1, 1)
                self.stackedWidgetContainer.addWidget(self.pageSetting)
                self.pageReminder = QtWidgets.QWidget()
                self.pageReminder.setObjectName("pageReminder")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageReminder)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.frame_3 = QtWidgets.QFrame(self.pageReminder)
                self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_3.setObjectName("frame_3")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
                self.verticalLayout_3.setContentsMargins(0, -1, 0, -1)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.labelReminder = QtWidgets.QLabel(self.frame_3)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.labelReminder.setFont(font)
                self.labelReminder.setObjectName("labelReminder")
                self.verticalLayout_3.addWidget(self.labelReminder)
                self.frame = QtWidgets.QFrame(self.frame_3)
                self.frame.setMinimumSize(QtCore.QSize(0, 0))
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.textEditReminder = QtWidgets.QTextEdit(self.frame)
                self.textEditReminder.setMinimumSize(QtCore.QSize(0, 2))
                self.textEditReminder.setMaximumSize(QtCore.QSize(16777215, 100))
                self.textEditReminder.setObjectName("textEditReminder")
                self.horizontalLayout_4.addWidget(self.textEditReminder)
                self.btnAddReminder = QtWidgets.QPushButton(self.frame)
                self.btnAddReminder.setObjectName("btnAddReminder")
                self.horizontalLayout_4.addWidget(self.btnAddReminder)
                self.verticalLayout_3.addWidget(self.frame)
                self.listWidgetReminders = QtWidgets.QListWidget(self.frame_3)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.listWidgetReminders.sizePolicy().hasHeightForWidth())
                self.listWidgetReminders.setSizePolicy(sizePolicy)
                self.listWidgetReminders.setMidLineWidth(1)
                self.listWidgetReminders.setAlternatingRowColors(False)
                self.listWidgetReminders.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
                self.listWidgetReminders.setTextElideMode(QtCore.Qt.ElideRight)
                self.listWidgetReminders.setProperty("isWrapping", True)
                self.listWidgetReminders.setLayoutMode(QtWidgets.QListView.SinglePass)
                self.listWidgetReminders.setViewMode(QtWidgets.QListView.ListMode)
                self.listWidgetReminders.setUniformItemSizes(False)
                self.listWidgetReminders.setWordWrap(True)
                self.listWidgetReminders.setSelectionRectVisible(True)
                self.listWidgetReminders.setObjectName("listWidgetReminders")
                item = QtWidgets.QListWidgetItem()
                font = QtGui.QFont()
                font.setItalic(False)
                item.setFont(font)
                item.setFlags(
                        QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                item.setCheckState(QtCore.Qt.Checked)
                self.listWidgetReminders.addItem(item)
                item = QtWidgets.QListWidgetItem()
                font = QtGui.QFont()
                font.setKerning(False)
                item.setFont(font)
                item.setFlags(
                        QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                item.setCheckState(QtCore.Qt.Checked)
                self.listWidgetReminders.addItem(item)
                item = QtWidgets.QListWidgetItem()
                item.setFlags(
                        QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsEditable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled)
                item.setCheckState(QtCore.Qt.Checked)
                self.listWidgetReminders.addItem(item)
                self.verticalLayout_3.addWidget(self.listWidgetReminders)
                self.frame_2 = QtWidgets.QFrame(self.frame_3)
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_2)
                self.horizontalLayout_8.setObjectName("horizontalLayout_8")
                self.btnDelete = QtWidgets.QPushButton(self.frame_2)
                self.btnDelete.setObjectName("btnDelete")
                self.horizontalLayout_8.addWidget(self.btnDelete)
                self.btnClearAll = QtWidgets.QPushButton(self.frame_2)
                self.btnClearAll.setObjectName("btnClearAll")
                self.horizontalLayout_8.addWidget(self.btnClearAll)
                spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                                    QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_8.addItem(spacerItem5)
                self.label_2 = QtWidgets.QLabel(self.frame_2)
                self.label_2.setObjectName("label_2")
                self.horizontalLayout_8.addWidget(self.label_2)
                self.verticalLayout_3.addWidget(self.frame_2)
                self.verticalLayout_2.addWidget(self.frame_3)
                self.stackedWidgetContainer.addWidget(self.pageReminder)
                self.pageTips = QtWidgets.QWidget()
                self.pageTips.setObjectName("pageTips")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageTips)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.textBrowser = QtWidgets.QTextBrowser(self.pageTips)
                self.textBrowser.setStyleSheet("")
                self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
                self.textBrowser.setOverwriteMode(False)
                self.textBrowser.setOpenExternalLinks(True)
                self.textBrowser.setOpenLinks(True)
                self.textBrowser.setObjectName("textBrowser")
                self.verticalLayout_4.addWidget(self.textBrowser)
                self.stackedWidgetContainer.addWidget(self.pageTips)
                self.gridLayout_3.addWidget(self.stackedWidgetContainer, 1, 1, 1, 1)
                self.frameLeftBar = QtWidgets.QFrame(self.frameMainWindow)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.frameLeftBar.sizePolicy().hasHeightForWidth())
                self.frameLeftBar.setSizePolicy(sizePolicy)
                self.frameLeftBar.setMinimumSize(QtCore.QSize(40, 0))
                self.frameLeftBar.setMaximumSize(QtCore.QSize(40, 16777215))
                self.frameLeftBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frameLeftBar.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frameLeftBar.setObjectName("frameLeftBar")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.frameLeftBar)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.btnToggle = QtWidgets.QPushButton(self.frameLeftBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnToggle.sizePolicy().hasHeightForWidth())
                self.btnToggle.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                self.btnToggle.setFont(font)
                self.btnToggle.setStyleSheet("color: rgb(255, 255, 255);text-align: left;")
                self.btnToggle.setText("")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap(":/icon/icons/hamburger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnToggle.setIcon(icon)
                self.btnToggle.setIconSize(QtCore.QSize(32, 32))
                self.btnToggle.setFlat(True)
                self.btnToggle.setObjectName("btnToggle")
                self.verticalLayout.addWidget(self.btnToggle)
                self.btnPageSetting = QtWidgets.QPushButton(self.frameLeftBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnPageSetting.sizePolicy().hasHeightForWidth())
                self.btnPageSetting.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnPageSetting.setFont(font)
                self.btnPageSetting.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                  "                       text-align: left;\n"
                                                  "                   ")
                icon1 = QtGui.QIcon()
                icon1.addPixmap(QtGui.QPixmap(":/icon/icons/icon_setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnPageSetting.setIcon(icon1)
                self.btnPageSetting.setIconSize(QtCore.QSize(32, 32))
                self.btnPageSetting.setFlat(True)
                self.btnPageSetting.setObjectName("btnPageSetting")
                self.verticalLayout.addWidget(self.btnPageSetting)
                self.btnPageReminder = QtWidgets.QPushButton(self.frameLeftBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnPageReminder.sizePolicy().hasHeightForWidth())
                self.btnPageReminder.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnPageReminder.setFont(font)
                self.btnPageReminder.setAutoFillBackground(False)
                self.btnPageReminder.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                   "                       text-align: left;\n"
                                                   "                   ")
                icon2 = QtGui.QIcon()
                icon2.addPixmap(QtGui.QPixmap(":/icon/icons/icon_message.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnPageReminder.setIcon(icon2)
                self.btnPageReminder.setIconSize(QtCore.QSize(32, 32))
                self.btnPageReminder.setFlat(True)
                self.btnPageReminder.setObjectName("btnPageReminder")
                self.verticalLayout.addWidget(self.btnPageReminder)
                self.btnPageTips = QtWidgets.QPushButton(self.frameLeftBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnPageTips.sizePolicy().hasHeightForWidth())
                self.btnPageTips.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnPageTips.setFont(font)
                self.btnPageTips.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "                       text-align: left;\n"
                                               "                   ")
                icon3 = QtGui.QIcon()
                icon3.addPixmap(QtGui.QPixmap(":/icon/icons/icon_file_text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnPageTips.setIcon(icon3)
                self.btnPageTips.setIconSize(QtCore.QSize(32, 32))
                self.btnPageTips.setFlat(True)
                self.btnPageTips.setObjectName("btnPageTips")
                self.verticalLayout.addWidget(self.btnPageTips)
                self.btnPageHelp = QtWidgets.QPushButton(self.frameLeftBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnPageHelp.sizePolicy().hasHeightForWidth())
                self.btnPageHelp.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnPageHelp.setFont(font)
                self.btnPageHelp.setToolTipDuration(-1)
                self.btnPageHelp.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.btnPageHelp.setStyleSheet("color: rgb(255, 255, 255);\n"
                                               "                       text-align: left;\n"
                                               "                   ")
                icon4 = QtGui.QIcon()
                icon4.addPixmap(QtGui.QPixmap(":/icon/icons/icon_help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnPageHelp.setIcon(icon4)
                self.btnPageHelp.setIconSize(QtCore.QSize(32, 32))
                self.btnPageHelp.setAutoExclusive(False)
                self.btnPageHelp.setFlat(True)
                self.btnPageHelp.setObjectName("btnPageHelp")
                self.verticalLayout.addWidget(self.btnPageHelp)
                self.gridLayout_3.addWidget(self.frameLeftBar, 1, 0, 1, 1)
                self.frameTitleBar = QtWidgets.QFrame(self.frameMainWindow)
                self.frameTitleBar.setStyleSheet("QFrame {\n"
                                                 "                             border-bottom: 1px solid #263238;\n"
                                                 "                             border-bottom-left-radius: 0;\n"
                                                 "                             border-bottom-right-radius: 0;\n"
                                                 "                             }\n"
                                                 "\n"
                                                 "                         ")
                self.frameTitleBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frameTitleBar.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frameTitleBar.setObjectName("frameTitleBar")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameTitleBar)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.label = QtWidgets.QLabel(self.frameTitleBar)
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setStyleSheet("color: rgb(0, 200, 83);\n"
                                         "                                         border: none;\n"
                                         "                                     ")
                self.label.setObjectName("label")
                self.horizontalLayout_2.addWidget(self.label)
                spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                                    QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem6)
                self.btnMinimize = QtWidgets.QPushButton(self.frameTitleBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnMinimize.sizePolicy().hasHeightForWidth())
                self.btnMinimize.setSizePolicy(sizePolicy)
                self.btnMinimize.setMinimumSize(QtCore.QSize(20, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnMinimize.setFont(font)
                self.btnMinimize.setStyleSheet("QPushButton {\n"
                                               "\n"
                                               "                                         background-color: rgb(0, 170, 0);\n"
                                               "                                         color: rgb(255, 255, 255);\n"
                                               "                                         border-radius: 10px;\n"
                                               "                                         }\n"
                                               "                                         QPushButton:hover {\n"
                                               "                                         background-color: rgb(0, 150, 0);\n"
                                               "                                         }\n"
                                               "                                     ")
                self.btnMinimize.setFlat(True)
                self.btnMinimize.setObjectName("btnMinimize")
                self.horizontalLayout_2.addWidget(self.btnMinimize)
                spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem7)
                self.btnMaximize = QtWidgets.QPushButton(self.frameTitleBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnMaximize.sizePolicy().hasHeightForWidth())
                self.btnMaximize.setSizePolicy(sizePolicy)
                self.btnMaximize.setMinimumSize(QtCore.QSize(20, 20))
                self.btnMaximize.setMaximumSize(QtCore.QSize(20, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnMaximize.setFont(font)
                self.btnMaximize.setStyleSheet("QPushButton {\n"
                                               "                                         background-color: rgb(255, 218, 7);\n"
                                               "                                         color: rgb(255, 255, 255);\n"
                                               "                                         border-radius: 10px;\n"
                                               "                                         }\n"
                                               "                                         QPushButton:hover {\n"
                                               "                                         background-color: rgb(255, 170, 0);\n"
                                               "                                         }\n"
                                               "                                     ")
                self.btnMaximize.setText("")
                icon5 = QtGui.QIcon()
                icon5.addPixmap(QtGui.QPixmap(":/icon/icons/icon_resize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnMaximize.setIcon(icon5)
                self.btnMaximize.setIconSize(QtCore.QSize(8, 8))
                self.btnMaximize.setFlat(True)
                self.btnMaximize.setObjectName("btnMaximize")
                self.horizontalLayout_2.addWidget(self.btnMaximize)
                spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
                self.horizontalLayout_2.addItem(spacerItem8)
                self.btnClose = QtWidgets.QPushButton(self.frameTitleBar)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.btnClose.sizePolicy().hasHeightForWidth())
                self.btnClose.setSizePolicy(sizePolicy)
                self.btnClose.setMinimumSize(QtCore.QSize(20, 20))
                self.btnClose.setMaximumSize(QtCore.QSize(20, 20))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.btnClose.setFont(font)
                self.btnClose.setStyleSheet("QPushButton {\n"
                                            "\n"
                                            "\n"
                                            "                                         background-color: rgb(255, 52, 55);\n"
                                            "                                         color: rgb(255, 255, 255);\n"
                                            "                                         border-radius: 10px;\n"
                                            "                                         }\n"
                                            "                                         QPushButton:hover {\n"
                                            "\n"
                                            "\n"
                                            "                                         background-color: rgb(170, 0, 0);\n"
                                            "                                         }\n"
                                            "                                     ")
                self.btnClose.setText("")
                icon6 = QtGui.QIcon()
                icon6.addPixmap(QtGui.QPixmap(":/icon/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.btnClose.setIcon(icon6)
                self.btnClose.setIconSize(QtCore.QSize(8, 8))
                self.btnClose.setFlat(True)
                self.btnClose.setObjectName("btnClose")
                self.horizontalLayout_2.addWidget(self.btnClose)
                self.gridLayout_3.addWidget(self.frameTitleBar, 0, 0, 1, 2)
                self.gridLayout_2.addWidget(self.frameMainWindow, 0, 0, 1, 1)
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                self.stackedWidgetContainer.setCurrentIndex(2)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Care your Eyes"))
                self.btnStop.setText(_translate("MainWindow", "Dừng"))
                self.groupBoxTypeRemind.setTitle(_translate("MainWindow", "Kiểu nhắc nhở:"))
                self.radioButtonType_Popup.setText(_translate("MainWindow", "Hộp thoại thông báo"))
                self.radioButtonType_Toast.setText(_translate("MainWindow", "Thông báo đẩy"))
                self.labelMinute.setText(_translate("MainWindow", "phút"))
                self.btnStart.setText(_translate("MainWindow", "Bắt đầu"))
                self.labelUserName.setText(_translate("MainWindow", "Tên của bạn:"))
                self.lineEditUserName.setPlaceholderText(_translate("MainWindow", "Name"))
                self.labelChooseTime.setText(_translate("MainWindow", "Chọn thời gian nhắc nhở:"))
                self.checkBoxShowTips.setText(_translate("MainWindow", "Hiển thị tips"))
                self.labelReminder.setText(_translate("MainWindow", "Tuỳ chỉnh lời nhắc:"))
                self.textEditReminder.setPlaceholderText(_translate("MainWindow", "Nhập lời nhắc của bạn vào đây"))
                self.btnAddReminder.setText(_translate("MainWindow", "Thêm"))
                self.listWidgetReminders.setStatusTip(_translate("MainWindow", "Nhấp đúp để chỉnh sửa"))
                __sortingEnabled = self.listWidgetReminders.isSortingEnabled()
                self.listWidgetReminders.setSortingEnabled(False)
                item = self.listWidgetReminders.item(0)
                item.setText(_translate("MainWindow", "Hãy để đôi mắt thân yêu của bạn nghỉ ngơi một lát đi nhé !"))
                item = self.listWidgetReminders.item(1)
                item.setText(_translate("MainWindow",
                                        "Hey! Đã khá lâu rồi bạn chưa thư giãn cho đôi mắt của bạn rồi đó nha! Làm ngay đi nào!"))
                item = self.listWidgetReminders.item(2)
                item.setText(_translate("MainWindow",
                                        "Bạn ơi bạn có thấy mỏi mắt không? Tại sao không dành một chút thời gian để thư giãn đôi mắt đi!"))
                self.listWidgetReminders.setSortingEnabled(__sortingEnabled)
                self.btnDelete.setText(_translate("MainWindow", "Xóa"))
                self.btnClearAll.setText(_translate("MainWindow", "Xóa tất cả"))
                self.label_2.setText(_translate("MainWindow", "* Nhấn đúp vào một dòng để chỉnh sửa"))
                self.textBrowser.setHtml(_translate("MainWindow",
                                                    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                    "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                    "p, li { white-space: pre-wrap; }\n"
                                                    "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Khi thường xuyên sử dụng máy tính hay các thiết bị điện tử khác như ti vi, điện thoại…, mắt dễ bị mỏi, khô, nhức. Bạn cần sử dụng sao cho đúng cách và chăm sóc mắt khi sử dụng máy tính khoa học giúp thị lực luôn ổn định, sức khỏe đôi mắt được đảm bảo.</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Cùng với sự phát triển của xã hội, nhu cầu sử dụng máy tính thường xuyên cũng trở nên phổ biến. Điều này đồng nghĩa với việc mắt sẽ phải làm việc nhiều hơn, đặc biệt là những người trẻ, nhân viên văn phòng. Bởi thế, việc sử dụng máy tính, máy tính bảng… đúng cách, cách chăm sóc mắt khoa học cũng có thể cải thiện được phần nào sức khỏe của đôi mắt.</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"toc_container\"></a><span style=\" font-size:12pt;\">N</span><span style=\" font-size:12pt;\">ội Dung Bài Viết</span></p>\n"
                                                    "<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#Mat_se_gap_van_de_gi_khi_thuong_xuyen_dung_may_tinh\"><span style=\" text-decoration: underline; color:#00aaff;\">1 Mắt sẽ gặp vấn đề gì khi thường xuyên dùng máy tính</span></a></li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#Nguyen_nhan_dan_den_cac_van_de_thi_giac_khi_dung_may_tinh\"><span style=\" text-decoration: underline; color:#00aaff;\">2 Nguyên nhân dẫn đến các vấn đề thị giác khi dùng máy tính</span></a></li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#Nguyen_tac_su_dung_may_tinh_va_cac_thiet_bi_dien_tu_dung_cach\"><span style=\" text-decoration: underline; color:#00aaff;\">3 Nguyên tắc sử dụng máy tính và các thiết bị điện tử đúng cách</span></a></li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"#Cham_soc_mat_khi_su_dung_may_tinh_dung_cach\"><span style=\" text-decoration: underline; color:#00aaff;\">4 Chăm sóc mắt khi sử dụng máy tính đúng cách</span></a></li></ul>\n"
                                                    "<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"Mat_se_gap_van_de_gi_khi_thuong_xuyen_dung_may_tinh\"></a><span style=\" font-size:12pt; font-weight:600;\">M</span><span style=\" font-size:12pt; font-weight:600;\">ắt sẽ gặp vấn đề gì khi thường xuyên dùng máy tính</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Theo một số nghiên cứu của Mỹ khoảng ba phần tư số người thường xuyên sử dụng máy vi tính gặp các rối loạn chức năng về mắt: căng thẳng hay mệt mỏi thị giác,</span><span style=\" font-size:12pt; color:#00aaff;\"> </span><a href=\"https://benhvienmatsaigon.com.vn/kho-mat-nguyen-nhan-trieu-chung-va-cach-dieu-tri/\"><span style=\" font-size:12pt; text-decoration: underline; color:#00aaff;\">khô mắt</span></a><span style=\" font-size:12pt;\">, cảm giác rát mắt, chói sáng, </span><a href=\"https://benhvienmatsaigon.com.vn/mat-bi-mo/\"><span style=\" font-size:12pt; text-decoration: underline; color:#00aaff;\">nhìn mờ</span></a><span style=\" font-size:12pt;\">, đau đầu và mỏi vai, mỏi cổ và lưng. Các triệu chứng này được gọi là</span><span style=\" font-size:12pt; color:#00aaff;\"> </span><a href=\"https://benhvienmatsaigon.com.vn/hoi-chung-thi-gac-may-tinh/\"><span style=\" font-size:12pt; text-decoration: underline; color:#00aaff;\">hội chứng về mắt do sử dụng máy vi tính</span></a><span style=\" font-size:12pt;\"> (CVS: Computer Vision Syndrom).</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Các nghiên cứu thời gian gần đây cho thấy chỉ cần 2 giờ ngồi trước màn hình máy tính, mọi người có thể bắt đầu gặp nguy hiểm với triệu chứng căng thẳng mắt. Thời gian được tính nhìn vào màn hình gồm cả máy tính, điện thoại, máy tính bảng và cả TV.</span></p>\n"
                                                    "<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"Nguyen_nhan_dan_den_cac_van_de_thi_giac_khi_dung_may_tinh\"></a><span style=\" font-size:12pt; font-weight:600;\">N</span><span style=\" font-size:12pt; font-weight:600;\">guyên nhân dẫn đến các vấn đề thị giác khi dùng máy tính</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Bên cạnh nhữngtác nhân gây hại như nắng, gió, khói bụi từ môi trường khi đi đường,…đôi mắtphải hoạt động, điều tiết liên tục cả ngày khi làm việc trước máy tính khiếncho mắt rất dễ rơi vào tình trạng nhức mỏi, đỏ, khô ngứa…</span></p>\n"
                                                    "<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Chiếu sáng kém hoặc quá nhiều, kèm với các tia phản xạ từ màn hình.</span></li>\n"
                                                    "<li style=\" font-size:12pt; font-weight:600;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Khoảng cách nhìn không đúng.</li>\n"
                                                    "<li style=\" font-size:12pt; font-weight:600;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ngồi sai tư thế.</li>\n"
                                                    "<li style=\" font-size:12pt; font-weight:600;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mắt có tật khúc xạ: Viễn thị, loạn thị, lão thị hay các rối loạn về điều tiết.</li>\n"
                                                    "<li style=\" font-size:12pt; font-weight:600;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Giảm lượng nước mắt đến giác mạc do giảm số lần chớp mắt hoặc bị khô mắt.</li>\n"
                                                    "<li style=\" font-size:12pt; font-weight:600;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Phối hợp các yếu tố trên.</li></ul>\n"
                                                    "<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"Nguyen_tac_su_dung_may_tinh_va_cac_thiet_bi_dien_tu_dung_cach\"></a><span style=\" font-size:12pt; font-weight:600;\">N</span><span style=\" font-size:12pt; font-weight:600;\">guyên tắc sử dụng máy tính và các thiết bị điện tử đúng cách</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Cần hiểu rõ những nguyên tắc sử dụng máy tính và các thiết bị điện tử như tivi, máy tính bảng, smartphone để giảm sự căng thẳng và sự khô mỏi cho mắt:</span></p>\n"
                                                    "<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Làm sạch màn hình máy tính</span>: Bụi và vết bẩn trên màn hình máy tính, tivi… là nguyên nhân làm cho màn hình bị mờ, khó đọc gây ra chứng mỏi mắt. Vì thế, làm sạch màn hình là một phương pháp đơn giản đầu tiên bạn nên áp dụng. Điều này có thể giúp giảm mỏi mắt khi phải làm việc hay xem tivi nhiều.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Quy tắc 20-20-20</span><span style=\" font-weight:600; font-style:italic;\">:</span> Khi làm việc, hãy nhớ quy tắc: Sau 20 phút làm việc, nghỉ khoảng 20 giây và nhìn ra khoảng cách xa khoảng 20 foot (khoảng 6 mét). Đôi mắt của chúng ta có các cơ để giúp chúng di chuyển và tập trung vào các vật thể. Nhưng nếu chúng ta nhìn vào màn hình trong cùng khoảng cách quá lâu thì cơ mắt sẽ giảm đi sự linh hoạt, khó điều chỉnh khi chúng ta di chuyển mắt hướng đến những khoảng cách khác.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Điều chỉnh độ sáng màn hình</span><span style=\" font-weight:600; font-style:italic;\">:</span> Màn hình sáng dễ làm bạn chảy nước mắt, khiến mắt nhanh mỏi.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Đeo kính thay vì sử dụng kính áp tròng</span><span style=\" font-weight:600; font-style:italic;\">:</span>  <a href=\"https://benhvienmatsaigon.com.vn/uu-va-nhuoc-diem-khi-deo-kinh-ap-trong/\"><span style=\" text-decoration: underline; color:#00aaff;\">Kính áp tròng</span></a> không thể bảo vệ mắt của bạn trước màn hình máy vi tính và sẽ làm mắt bạn bị khô. Hãy chuyển sang kính gọng.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Dùng kính chống lóa</span><span style=\" font-weight:600; font-style:italic;\">:</span> Nếu phải dùng kính, hãy thêm lớp chống lóa để bảo vệ mắt. Tất cả nhà cung cấp kính chăm sóc đeo mắt đều có bán lớp kính này.</li>\n"
                                                    "<li style=\" font-size:12pt; color:#00ff7f;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Giữ khoảng cách vừa phải với màn hình</span>: <span style=\" color:#ffffff;\">Luôn duy trì một khoảng cách khá xa với màn hình máy tính trong khi làm việc. Đó là lý do tại sao sử dụng máy tính để bàn lại tốt hơn so với máy tính bảng và máy tính xách tay.</span></li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Tăng font chữ</span>: Khi phải đọc hay viết nhanh, hãy để phông chữ to để mắt không phải điều tiết quá nhiều, giảm áp lực lên đôi mắt.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Dùng kính không độ</span><span style=\" font-weight:600; font-style:italic;\">:</span> Cho dù mắt bạn hoàn toàn khỏe mạnh, bạn vẫn nên sử dụng kính không độ để chống lại ánh sáng từ màn hình.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Thêm màn hình bảo vệ thị lực</span><span style=\" font-weight:600; font-style:italic;\">:</span> Một số người đã gắn thêm một màn hình bảo vệ thị lực trên máy vi tính để bảo vệ mắt. Đây có thể là một trong những cách tốt nhất để giảm căng thẳng cho đôi mắt của bạn. </li></ul>\n"
                                                    "<p style=\" margin-top:16px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"Cham_soc_mat_khi_su_dung_may_tinh_dung_cach\"></a><span style=\" font-size:12pt; font-weight:600;\">C</span><span style=\" font-size:12pt; font-weight:600;\">hăm sóc mắt khi sử dụng máy tính đúng cách</span></p>\n"
                                                    "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Cách </span><a href=\"https://benhvienmatsaigon.com.vn/category/hieu-ve-doi-mat/\"><span style=\" font-size:12pt; text-decoration: underline; color:#00aaff;\">chăm sóc mắt</span></a><span style=\" font-size:12pt;\"> tốt nhất, hiệu quả nhất chắc chắn là việc điều chỉnh thời gian làm việc với máy tính vì nếu làm việc quá sức là tác nhân nguy hiểm nhất khiến mắt bị mệt mỏi.</span></p>\n"
                                                    "<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" font-size:12pt;\" style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Chớp mắt thường xuyên</span><span style=\" font-weight:600; font-style:italic;\">:</span> Mải làm việc khiến nhiều người quên chớp mắt trong thời gian dài. Chớp mắt thường xuyên giúp mắt không bị khô và mỏi.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Massage cho đôi mắt</span><span style=\" font-weight:600; font-style:italic;\">:</span> Nên massage đôi mắt mỗi ngày bằng cách: dùng hai bàn tay cọ xát vào nhau cho nóng lên rồi sau đó áp lên đôi mắt, vuốt nhẹ từ trong ra ngoài, dùng tay day nhẹ nhàng đôi mắt. Bạn cũng có thể cắt lát dưa chuột hoặc cà chua rồi đắp lên đôi mắt để mắt được thư giãn hơn.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Dùng</span><span style=\" font-weight:600; font-style:italic;\"> </span><a href=\"https://benhvienmatsaigon.com.vn/thuoc-nho-mat/\"><span style=\" font-weight:600; font-style:italic; text-decoration: underline; color:#00ff7f;\">thuốc nhỏ mắt</span></a><span style=\" font-weight:600; font-style:italic;\">:</span> Sau một ngày làm việc mệt mỏi, chúng ta nên dùng thuốc nhỏ mắt vào mỗi buổi tối để giúp mắt sáng khoẻ. Hãy nhắm mắt lại và thư giãn. Mắt cần được cung cấp nước cũng như loại bỏ những màng mờ trên mắt. Bạn có thể xin ý kiến tư vấn của bác sĩ để lựa chọn loại thuốc nhỏ mắt thích hợp cho mình. Trường hợp cần thiết, cảm giác có cộm xốn bụi mắt nên nhỏ vài giọt thuốc sát khuẩn nhẹ.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Bảo vệ mắt khi ngủ</span><span style=\" font-weight:600; font-style:italic;\">:</span> Nên hạn chế ánh sáng tối đa bởi vì ánh sáng kích thích thị giác, tạo hưng phấn vỏ não gây khó ngủ. Nên mở cửa sổ cho thông thoáng vì lúc ngủ mắt cũng cần oxy để “thở”.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Không nheo mắt, liếc mắt</span><span style=\" font-weight:600; font-style:italic;\">:</span> Máy vi tính, máy tính bảng và điện thoại thông minh đều có chức năng phóng to để bạn có thể đọc dễ dàng hơn. Nheo mắt thì có hại cho đôi mắt của bạn.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">Đảo mắt</span>: Làm việc quá tập trung khiến mắt căng và mỏi. Mở mắt to và đào mắt sẽ là bài tập thư giãn rất tốt cho mắt của bạn.</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">Về </span><span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">chế độ ăn uống</span>, bạn cần tăng cường ăn các loại rau có lá màu xanh thẫm, các loại trái cây có màu đỏ, vàng để bổ xung Vitamin A. Bạn cũng có thể uống một số loại thuốc để tăng cường dinh dưỡng cho mắt như là dầu cá… (tham khảo: <a href=\"https://benhvienmatsaigon.com.vn/thuc-pham-tot-cho-mat/\"><span style=\" text-decoration: underline; color:#00aaff;\">9 thực phẩm tốt cho mắt nên ăn hàng ngày</span></a>)</li>\n"
                                                    "<li style=\" font-size:12pt;\" style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nên <span style=\" font-weight:600; font-style:italic; color:#00ff7f;\">đi khám mắt định kỳ</span> 6 tháng một lần tại các<span style=\" color:#00aaff;\"> </span><a href=\"https://benhvienmatsaigon.com.vn/\"><span style=\" text-decoration: underline; color:#00aaff;\">bệnh viện mắt</span></a> chuyên khoa để điều chỉnh kính cho phù hợp vì đeo sai số kính cũng là một nguyên nhân khiến mắt nhức mỏi.</li></ul>\n"
                                                    "<p style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Nguồn: </span><a href=\"https://benhvienmatsaigon.com.vn/cham-soc-mat-khi-su-dung-may-tinh/\"><span style=\" font-size:12pt; text-decoration: underline; color:#ffffff;\">https://benhvienmatsaigon.com.vn/cham-soc-mat-khi-su-dung-may-tinh/</span></a></p></body></html>"))
                self.btnToggle.setToolTip(_translate("MainWindow", "Mở rộng"))
                self.btnPageSetting.setToolTip(_translate("MainWindow", "Thiết lập chung"))
                self.btnPageSetting.setText(_translate("MainWindow", "Chung"))
                self.btnPageReminder.setToolTip(_translate("MainWindow", "Kiểu thông báo"))
                self.btnPageReminder.setText(_translate("MainWindow", "Lời nhắc"))
                self.btnPageTips.setToolTip(_translate("MainWindow", "Lời nhắc"))
                self.btnPageTips.setText(_translate("MainWindow", "Tips"))
                self.btnPageHelp.setToolTip(_translate("MainWindow", "Help"))
                self.btnPageHelp.setText(_translate("MainWindow", "Help"))
                self.label.setText(_translate("MainWindow", "Care Your Eyes"))
                self.btnMinimize.setToolTip(_translate("MainWindow", "Minimize"))
                self.btnMinimize.setText(_translate("MainWindow", "-"))
                self.btnMaximize.setToolTip(_translate("MainWindow", "Maximize"))
                self.btnClose.setToolTip(_translate("MainWindow", "Close"))


import appresources_rc
